export enum ActionType{
    MENU_START = "[MENU] MENU START",
    MENU_SUCCESS = "[MENU] MENU SUCCESS",
    MENU_ERROR = "[MENU] MENU ERROR",
    FLOORTYPE_START = "[FLOOR] FLOOR START",
    FLOORTYPE_SUCCESS = "[FLOOR] FLOOR SUCCESS",
    FLOORTYPE_ERROR = "[FLOOR] FLOOR ERROR",
}